<?php
/**
 * @file
 * The ACK menu module.
 */

/**
 * Implements hook_permission().
 */
function ack_menu_permission() {
  return array(
    'manage access realm menu tree' => array(
      'title' => t('Manage the menu tree for an access realm'),
      'description' => t('Create and edit links within a realm-associated menu tree.'),
    ),
    'administer access realm menu map' => array(
      'title' => t('Administer the menu link-to-realm map'),
    ),
  );
}

/**
 * Implements hook_access_info().
 */
function ack_menu_access_info() {
  // Declare support for controlling access to menu links.
  $info['menu_link'] = array(
    'label' => t('Menu link'),
    'handlers' => array(),
    'permissions' => array('manage access realm menu tree' => TRUE),
  );

  // Handler to map menu links to realms; should work for all realm types.
  $info['menu_link']['handlers']['ACKMenuMap'] = array(
    'label' => t('mapping links to realms'),
    'realm types' => array_keys(access_realm_info()),
  );

  return $info;
}

/**
 * Implements hook_menu_alter().
 */
function ack_menu_menu_alter(&$items) {
  // Override access to the menu link admin pages.
  foreach (array('edit', 'reset', 'delete') as $op) {
    $items['admin/structure/menu/item/%menu_link/' . $op]['access callback'] = 'ack_menu_link_access';
    $items['admin/structure/menu/item/%menu_link/' . $op]['access arguments'] = array(4, $op);
  }
}

/**
 * Checks menu link access; used as the menu access callback for link admin.
 *
 * @param $menu_link
 *   A menu link object on which to perform the access check.
 * @param $op
 *   The operation to be performed.  Possible values:
 *   - "edit"
 *   - "reset"
 *   - "delete"
 * @param $account
 *   (optional) The user object on which to perform the access check operation.
 *   Defaults to the currently logged-in user.
 *
 * @return
 *   Boolean indicating whether the operation is allowed.
 */
function ack_menu_link_access($menu_link, $op, $account = NULL) {
  global $user;
  if (!isset($account)) {
    $account = $user;
  }

  // The 'administer menu' permission is global.
  if (user_access('administer menu', $account)) {
    return TRUE;
  }

  // Check realm permissions.
  switch ($op) {
    case 'edit':
    case 'reset':
    case 'delete':
      return access_user_object_access('manage access realm menu tree', 'menu_link', $menu_link, $account);
  }

  return FALSE;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ack_menu_form_node_form_alter(&$form, &$form_state, $form_id) {
  // @todo Filter the menu parent selector.
}
