<?php
/**
 * @file
 * The ACK node module.
 */

/**
 * Implements hook_access_object_info().
 */
function ack_node_access_object_info() {
  // Declare support for controlling access to nodes.
  $info['node'] = array(
    'label' => t('Content'),
    'handlers' => array(),
    'permissions' => array(),
  );

  // Handlers for node properties.
  $info['node']['handlers']['author'] = array(
    'label' => t('is author'),
    'realm types' => array('user'),
    'class' => 'ACKNodeAuthor',
  );
  $info['node']['handlers']['sticky'] = array(
    'label' => t('is sticky'),
    'realm types' => array('boolean'),
    'class' => 'ACKNodeSticky',
  );

  // Handlers for list fields.
  if (module_exists('list')) {
    $info['node']['handlers']['list'] = array(
      'label' => t('a list field'),
      'realm types' => array('list_integer', 'list_float', 'list_text'),
      'class' => 'ACKNodeList',
    );
  }

  // Handlers for taxonomy.
  if (module_exists('taxonomy')) {
    $info['node']['handlers']['taxonomy_index'] = array(
      'label' => t('term association'),
      'realm types' => array('taxonomy_term'),
      'class' => 'ACKNodeTaxonomyIndex',
    );
    $info['node']['handlers']['taxonomy_term'] = array(
      'label' => t('a term reference field'),
      'realm types' => array('taxonomy_term'),
      'class' => 'ACKNodeTaxonomyTermReference',
    );
  }

  // List the permissions for which we are providing ACK compatibility.
  foreach (node_permissions_get_configured_types() as $type) {
    $perms = node_list_permissions($type);
    foreach ($perms as $perm => $description) {
      $info['node']['permissions'][$perm] = TRUE;
    }
  }

  return $info;
}
